name: Changed files
on:
  push:
    branches: [ master ]

jobs:
  changed-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Checkout the code from the repository

      - name: Get changed files
        if: inputs.branch == ''
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            container/**
          dir_names: "true" # return only directory names
          separator: " " # multi-line output results in the error due to the new GITHUB OUTPUT variable
          dir_names_max_depth: 2 # return folder name in the format `container/<image-name>`
